apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: {{.cluster_name.value}}
spec:
  api:  
    loadBalancer:
      type: Public
      additionalSecurityGroups: ["{{.k8s_api_http_security_group_id.value}}"]
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    environment: dev
    owner: {{.cluster_name.value}}
    solution: kubernetes
  cloudProvider: aws
  configBase: s3://{{.kops_s3_bucket_name.value}}/{{.cluster_name.value}}
  dnsZone: {{.dns_zone.value}} 
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-ig
      name: a
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-ig
      name: a
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.10
  masterInternalName: api.internal.{{.cluster_name.value}}
  masterPublicName: api.{{.cluster_name.value}}
  networkCIDR: {{.vpc_cidr_block.value}} 
  networkID: {{.vpc_id.value}}
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  {{range $i, $id := .private_subnets.value}}
  - id: {{.}}
    cidr: {{index $.private_subnets_cidr_blocks.value $i}}
    type: Private
    name: private-{{index $.azs.value $i}}
    zone: {{index $.azs.value $i}}
  {{end}}
  {{range $i, $id := .public_subnets.value}}
  - id: {{.}}
    cidr: {{index $.public_subnets_cidr_blocks.value $i}}
    type: Utility
    name: utility-{{index $.azs.value $i}}
    zone: {{index $.azs.value $i}}
  {{end}}
  topology:
    dns:
      type: Private
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-19T12:53:29Z
  generation: 1
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: master-ig
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5.large
    - t3.medium
    - c4.large
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-ig
  role: Master
  subnets:
  - private-us-east-1a
---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-09-19T12:53:30Z
  generation: 2
  labels:
    kops.k8s.io/cluster: {{.cluster_name.value}}
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t3.large
  maxSize: 1
  minSize: 1
  mixedInstancesPolicy:
    instances:
    - m5.large
    - t3.medium
    - c4.large
    onDemandAboveBase: 0
    onDemandBase: 0
    spotInstancePools: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnet:
  - private-us-east-1a
  - private-us-east-1b
